name: ie-bank-infra-uat

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP_UAT: aguadamillas_students_1
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: chiaradigi
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  deploy-uat:
#   if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'User Acceptance Testing'
    env:
      ENV: uat
      DBHOST: chiaradigi-dbsrv-uat.postgres.database.azure.com
      DBNAME: chiaradigi-db-uat
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      RESOURCE_GROUP_UAT: aguadamillas_students_1
      SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

    steps:

      # Checkout code
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json appServiceAPIEnvVarENV=${{ env.ENV }} appServiceAPIEnvVarDBHOST=${{ env.DBHOST }} appServiceAPIEnvVarDBNAME=${{ env.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}